version: '3.9'

services:
  app:
    image: ghcr.io/mdejesus23/prep-app:latest
    container_name: preparation-app
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  caddy:
    image: caddy:alpine
    container_name: caddy-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
