version: '3.9'

services:
  app:
    build: .
    container_name: preparation-app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app # mount your local project folder into the container
      - /app/node_modules # prevent overwriting node_modules inside container
    command: npm run start:dev # use nodemon for hot reload in dev
